# Generated by Django 5.0.1 on 2024-04-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0003_alter_production_producers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='comments_cgArtist',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task2',
            name='comments_producer',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task2',
            name='comments_supervisor2',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task2',
            name='producerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_tasks2', to='BASE.producer2'),
        ),
    ]
