# Generated by Django 5.0.1 on 2024-04-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CgArtist3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('LIGHT', 'lighting'), ('COMP', 'compositing'), ('ANIM', 'animation'), ('MODEL', 'modelling'), ('SURFACE', 'surfacing'), ('FX', 'fx'), ('RIG', 'rigging')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('client', models.CharField(default='client-default', max_length=50)),
                ('producers', models.ManyToManyField(related_name='prods', to='BASE.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('lighting', 'lighting'), ('compositing', 'compositing'), ('animation', 'animation'), ('modelling', 'modelling'), ('surfacing', 'surfacing'), ('fx', 'fx'), ('rigging', 'rigging')], max_length=50)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateDue', models.DateField(blank=True, null=True)),
                ('comments_cgArtist', models.JSONField(default=list)),
                ('comments_supervisor2', models.JSONField(default=list)),
                ('comments_producer', models.JSONField(default=list)),
                ('versions', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('PRODUCTIONId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks2', to='BASE.production')),
                ('cgArtist3Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cg_artist3_tasks2', to='BASE.cgartist3')),
                ('producerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_tasks2', to='BASE.producer')),
                ('supervisor2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor2_tasks2', to='BASE.supervisor2')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
