# Generated by Django 5.0.1 on 2024-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0002_remove_cgartist3_email_remove_producer2_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='producers',
            field=models.ManyToManyField(related_name='prods', to='BASE.producer2'),
        ),
    ]
